framework:
    default_locale: '%env(default:default_locale:APP_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:

parameters:
    default_locale: fr
    app.supported_locales: ['fr', 'en']
